language: c

# Setting sudo to false opts in to Travis-CI container-based builds.
sudo: false

# Turn off email notifications
notifications:
  email: false

matrix:
  include:
    - os: linux
      env: PYTHON_VERSION="3.5"
    - os: linux
      env: PYTHON_VERSION="3.6"
    - os: osx
      osx_image: xcode9.4
      env: PYTHON_VERSION="3.5"
    - os: osx
      osx_image: xcode9.4
      env: PYTHON_VERSION="3.6"

cache:
  directories:
    - $TRAVIS_BUILD_DIR/quest_test_cache
    - $HOME/Quest

# commands to install quest
install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      OS_VERSION="Linux";
      SED_OPTIONS="-i";
    else
      OS_VERSION="MacOSX";
      SED_OPTIONS="-i ''";
    fi
  # We do this conditionally because it saves us some downloading if the
  # version is the same.
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-${OS_VERSION}-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a
  # Create quest conda env and install deps
  - sed $SED_OPTIONS "s/python=3/python=$PYTHON_VERSION/" conda_environment.yml
  - conda env create -q -n test-environment -f conda_environment.yml
  - source activate test-environment
  - python setup.py install
  - conda list
  - export QUEST_CACHE_DIR=$TRAVIS_BUILD_DIR/quest_test_cache
  - export COVERAGE=$HOME/miniconda/envs/test-environment/lib/python$PYTHON_VERSION/site-packages/quest
  - python -c "import quest; quest.api.update_settings(dict(CACHE_DIR='$QUEST_CACHE_DIR')); quest.api.save_settings()"

# command to run tests
script:
  - if [[ "$TRAVIS_EVENT_TYPE" == "cron" ]]; then
      pytest --cov=$COVERAGE -vv --update-cache --nbval-lax examples/notebooks -m "";
    else
      pytest --cov=$COVERAGE -vv --nbval-lax examples/notebooks;
    fi


# generate test coverage information
after_success:
  coveralls
