environment:
  global:
    # SDK v7.0 MSVC Express 2008's SetEnv.cmd script will fail if the
    # /E:ON and /V:ON options are not enabled in the batch script intepreter
    # See: http://stackoverflow.com/a/13751649/163740
    CMD_IN_ENV: "cmd /E:ON /V:ON /C .\\tools\\appveyor\\run_with_env.cmd"
  matrix:
    - PYTHON_VERSION: 2.7
      MINICONDA: C:\Miniconda
      ENV_FILE: py2_conda_environment.yml
    - PYTHON_VERSION: 3.4
      MINICONDA: C:\Miniconda3
      ENV_FILE: py3_conda_environment.yml
    - PYTHON_VERSION: 3.5
      MINICONDA: C:\Miniconda3
      ENV_FILE: py3_conda_environment.yml
    - PYTHON_VERSION: 3.6
      MINICONDA: C:\Miniconda3
      ENV_FILE: py3_conda_environment.yml

init:
  - "ECHO %PYTHON_VERSION% %MINICONDA%"

install:
  # Install miniconda using a powershell script.
  - "set PATH=%MINICONDA%;%MINICONDA%\\Scripts;%PATH%"
  - "conda config --set always_yes yes --set changeps1 no"
  - "conda update -q conda"
  - "conda info -a"
  - "conda install python=%PYTHON_VERSION%"
  - "conda env create -q -n test-environment -f %ENV_FILE%"
  - "activate test-environment"
  - "python setup.py install"

test_script:
  - "%CMD_IN_ENV% python setup.py test"
