# conda environment file for python 3, includes packages needed for testing
# create a conda virtual env using:
#   conda env create -n myenv --file py3_conda_environment.yml
#   source activate myenv (use 'activate myenv' on windows)
#   python setup.py develop
#
# optionally run tests:
#   python setup.py test

name: dsl

channels:
    - ioos

dependencies:
    - python=3.4
    - gdal
    - fiona>=1.5.1
    - rasterio>=0.23.0
    - numpy
    - geojson
    - jsonschema
    - ulmo>=0.8.1
    - pyoos
    - pyyaml
    - matplotlib>=1.4.0
    - click
    - werkzeug
    - pip:
      - json-rpc
      - jsonrpc-requests
      - peewee
      - stevedore
